#! /bin/sh
# prep - Move a binary distribution file to the application daemon
#        user's webapps directory and set the group ownership
#        and file permissions of the file so that the application daemon
#        user can manipulate the file. 
#      - 09/23/08, Russell Tokuyama
#
# $Id$
#
# Mod: 
#      2010-03-10 jbeutel@hawaii.edu; parameterize and allow for overrides
#      2015-12-02 cahana@hawaii.edu; commented out check to ensure the user running the script is not the daemon/app user
#
# Preconditions:
#   1. The distribution should be named like ${CTX_NAME}.war (see the
#      code below).
#   2. The user running this script must be in the same group as the
#      $APP_USER.
#
# USAGE: (as your regular user in the directory where you have the
#         distribution)
#
#   $ ~${APP_USER}/prep
#
# USAGE: (as daemon/app user in home directory where you have the
#         distribution)
#
#   $ ./prep
#
#---------------------------------------------------------------------
# Install:
#   1. Install as prep-common in /usr/local/bin/appDaemon.
#   2. Symlink from /usr/local/bin/appDaemon/prep-common to prep in APP_USER's home dir.
#   3. For convenience, add APP_USER's home dir to PATH env var.

# You shouldn't need to change variable settings in this script;
# you can override all variables like FOO=${FOO:-default} in the app.parameters file.

# include parameters from same dir as this script
PARAM_FILE=`dirname $0`/app.parameters
if [ ! -f $PARAM_FILE ] ; then
  echo "$PARAM_FILE not found" 1>&2
  exit 1
fi
. $PARAM_FILE

# make sure we got the required parameters
APP_USER=${APP_USER:?}
APP_GRP=${APP_GRP:?}
CTX_NAME=${CTX_NAME:?}

# Binary distribution must be named like so:
DIST=${DIST:-${CTX_NAME}.war}

# default
if [ `uname` = "SunOS" ]; then
  APP_HOME=${APP_HOME:-/var/home/${APP_USER}}
else
  APP_HOME=${APP_HOME:-/home/${APP_USER}} # on Linux
fi

# defaults
CATALINA_BASE=${CATALINA_BASE:-${APP_HOME}/tomcat}
WEBAPPS_DIR=${WEBAPPS_DIR:-${CATALINA_BASE}/webapps}

CURR_USER=`id | sed 's/[^(]*(\([^)]*\)).*$/\1/'`

#if [ ${CURR_USER} = ${APP_USER} ] ; then
#  echo "You must not be the ${APP_USER} when running this command."
#  echo "Exit to become your regular user."
#  exit 1
#fi

if [ ! -f ${DIST} ] ; then
  echo "${DIST} not found"
  exit 1
fi

if [ ! -d ${WEBAPPS_DIR} ] ; then
  echo "${WEBAPPS_DIR} not found"
  exit 1
fi

# Move file to application daemon user's servlet directory.
echo "Copying ${DIST} to ${WEBAPPS_DIR} ..."
DT=`date '+%y%m%d-%H%M'`
# Only keep one previous war file.
/bin/rm ${WEBAPPS_DIR}/${DIST}-*
/bin/mv ${WEBAPPS_DIR}/${DIST}  ${WEBAPPS_DIR}/${DIST}-${DT}
/bin/cp ./${DIST} ${WEBAPPS_DIR}

# set the file access mode 
echo "Setting file access on ${DIST}..."
chmod 660 ${WEBAPPS_DIR}/${DIST}

# set group ownership
echo "Setting group ownership of ${DIST}..."
chgrp ${APP_GRP} ${WEBAPPS_DIR}/${DIST}

echo
echo "Done."
echo "Now switch to ${APP_USER} and do the following:"
echo "  1. Stop the application, using \"app stop\" (i.e., \"sudo /bin/systemctl stop tomcat_${APP_USER}\")"
echo "  2. Run the \"deploy\" command to redeploy the WAR file."
echo "  3. Be sure that your app's configuration files are set properly."
echo "  4. Start the application, using \"app start\" (i.e., \"sudo /bin/systemctl start tomcat_${APP_USER}\")"

# eof: prep
